######################################################################
# Automatically generated by qmake (2.01a) Fri Jun 24 09:26:04 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
